services:
  mongodb:
    image: mongo:8.0.14-rc0
    container_name: mongodb
    restart: always

    ports:
      - "27017:27017"

    volumes:
      - mongodata:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    networks:
      - backend

networks:
  backend:

volumes:
  mongodata:
